<a href="https://colab.research.google.com/github/Sagargupta16/ML-Lab-Codes/blob/main/ML_LAB_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import scipy as sp
import pandas as pd

In [2]:
# Q-1

X = np.random.randint(1,10,size=(5,6))
Y = np.random.randint(1,10,size=(5,6))

print("Two Random Integer Matrices of 5X6 are : ")
print("1st Matrix is : ")
print(X)

print("2nd Matrix is : ")
print(Y)

XT = X.T
YT = Y.T
print("Transpose of 1st Matrix is : ")
print(XT)
print("Transpose of 2nd Matrix is : ")
print(YT)

XX = np.dot(X,XT)
YY = np.dot(Y,YT)
print("Dot Product of 1st matrix and its Transpose is : ")
print(XX)

print("Dot Product of 2nd matrix and its Transpose is : ")
print(YY)

ans = 12*XX+(15*YY)^2+108
print("Performing 12*X.XT + 15*(Y.YT)^2 + 108 Operation Matrix is : ")
print(ans)


print("Trace of Final answer is : " )
print(np.trace(ans))

Two Random Integer Matrices of 5X6 are : 
1st Matrix is : 
[[3 5 6 1 9 3]
 [1 1 4 6 7 6]
 [9 3 7 3 7 8]
 [9 1 2 9 1 1]
 [5 1 8 3 6 3]]
2nd Matrix is : 
[[8 3 9 2 7 1]
 [7 8 1 6 6 1]
 [4 3 9 1 4 3]
 [7 1 4 8 7 2]
 [3 3 5 9 9 7]]
Transpose of 1st Matrix is : 
[[3 1 9 9 5]
 [5 1 3 1 1]
 [6 4 7 2 8]
 [1 6 3 9 3]
 [9 7 7 1 6]
 [3 6 8 1 3]]
Transpose of 2nd Matrix is : 
[[8 7 4 7 3]
 [3 8 3 1 3]
 [9 1 9 4 5]
 [2 6 1 8 9]
 [7 6 4 7 9]
 [1 1 3 2 7]]
Dot Product of 1st matrix and its Transpose is : 
[[161 119 174  65 134]
 [119 139 155  85 116]
 [174 155 261 140 179]
 [ 65  85 140 169  98]
 [134 116 179  98 144]]
Dot Product of 2nd matrix and its Transpose is : 
[[208 144 155 162 166]
 [144 187  94 153 165]
 [155  94 132 109 132]
 [162 153 109 183 193]
 [166 165 132 193 254]]
Performing 12*X.XT + 15*(Y.YT)^2 + 108 Operation Matrix is : 
[[5074 3690 4435 3300 4204]
 [3690 4375 3240 3229 3957]
 [4435 3240 5014 3229 4174]
 [3300 3229 3229 4811 3977]
 [4204 3957 4174 3977 5580]]
Trace of Final answ

In [ ]:
# Q-2
data = pd.read_csv("train.csv")

# A
c_below_10 = data[data['Age'] < 10]
c_survived = c_below_10[c_below_10['Survived'] == 1]
print("Number of children below 10 survived:", len(c_survived))
print("Total number of children below 10:", len(c_below_10))
print()

# B
sur_class = data.groupby('Pclass')['Survived'].mean() * 100
print("Survival percentage by passenger class:")
for classs,i in sur_class.items():
    print(f"Class {classs} Survival Percentage:", i)
print()

# C
sur_gender = data.groupby('Sex')['Survived'].mean() * 100
print("Survival percentage by gender:")
for gender,i in sur_gender.items():
    print(f"{gender} Survival Percentage:", i)

Number of children below 10 survived: 38
Total number of children below 10: 62

Survival percentage by passenger class:
Class 1 Survival Percentage: 62.96296296296296
Class 2 Survival Percentage: 47.28260869565217
Class 3 Survival Percentage: 24.236252545824847

Survival percentage by gender:
female Survival Percentage: 74.20382165605095
male Survival Percentage: 18.890814558058924


In [8]:
# Q-3
import numpy as np
from scipy.optimize import fsolve

# Define the system of equations
def equations(vars):
    x, y = vars
    eq1 = x**2 + y**3 + 2*x*y + 5
    eq2 = x + y - 6
    return [eq1, eq2]

# Initial guess
initial_guess = [54, 6]

# Solve the system of equations
solution = fsolve(equations, initial_guess)

print("Solution:")
print("x =", solution[0])
print("y =", solution[1])


Solution:
x = 9.145047308291792
y = -3.1450473082917934
